version: "3.8"
name: dockertut
services:
  nodeapp:
    image: dockertutapp
    container_name: dockertutapp
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://admin:password@mongodb
    ports:
      - 4000:4000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: dockertutdb
    ports:
      - 27071:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  authservice:
    image: dockertutauth
    ports:
      - 5000:5000
    depends_on:
      - nodeapp
    environment:
      - PORT=5000
  client:
    image: dockertutclient
    ports:
      - 3000:3000
    depends_on:
      - authservice
