name: dockertut
services:
  nodeapp:
    build:
      context: ./myapp
      dockerfile: Dockerfile
    container_name: dockertutapp
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://admin:password@mongodb
    env_file:
      - .env.sample
    ports:
      - 4000:4000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: dockertutdb
    ports:
      - 27071:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - dockertutdata:/data/db
      # - dockertutdb:/data/db
      # - ./data:/data/db

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: dockertutauth
    ports:
      - 5000:5000
    depends_on:
      - nodeapp
    environment:
      - PORT=5000
  client:
    build:
      context: ./client
      # dockerfile: Dockerfile # build
      dockerfile: development.Dockerfile # dev
    container_name: dockertutclient
    ports:
      - 3000:3000
    environment:
      - SERVER_URL=http://nodeapp:4000
    depends_on:
      - auth
    volumes:
      - ./client:/app
volumes:
  # dockertutdb:
  dockertutdata:
    driver: local